# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "pycon"
    v.memory = 1536
    v.cpus = 2
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision :shell, path: "provision.sh", privileged: false
  config.vm.synced_folder "../", "/home/vagrant/project/"
  # config.vm.network "forwarded_port", guest: 8000, host: 8000
  # config.vm.network "forwarded_port", guest: 21, host: 21
  # config.vm.network "forwarded_port", guest: 9000, host: 9000

end
